services:
  backend:
    build: ./backend
    restart: always
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - BOT_LINK=${BOT_LINK}
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    networks:
      network:
        ipv4_address: 67.16.1.5

  frontend:
    build:
      context: ./tg-mini-app-master
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./tg-mini-app-master:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      network:
        ipv4_address: 67.16.1.7

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - 9088:9088
    restart: always
    volumes:
      - ./gateway/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      network:
        ipv4_address: 67.16.1.6

  bot:
    build: ./tg-bot
    restart: always
    depends_on:
      - backend
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - BOT_LINK=${BOT_LINK}
      - WEBAPP_URL=${WEBAPP_URL}
    volumes:
      - ./tg-bot:/app
    networks:
      network:
        ipv4_address: 67.16.1.153

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 67.16.0.0/16
          gateway: 67.16.0.1
