"""add free daily boost columns

Revision ID: 0dc2d412a26b
Revises: 39521ec5b458
Create Date: 2024-09-10 04:13:35.553905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dc2d412a26b'
down_revision: Union[str, None] = '39521ec5b458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boosters', sa.Column('turbo_range_uses', sa.Integer(), nullable=True))
    op.add_column('boosters', sa.Column('x_leverage_uses', sa.Integer(), nullable=True))
    op.add_column('boosters', sa.Column('last_reset', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boosters', 'last_reset')
    op.drop_column('boosters', 'x_leverage_uses')
    op.drop_column('boosters', 'turbo_range_uses')
    # ### end Alembic commands ###
