"""fix clans model

Revision ID: 11111099d8ad
Revises: 7067b63501dc
Create Date: 2024-08-06 19:07:05.985907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11111099d8ad'
down_revision: Union[str, None] = '7067b63501dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clans', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leagues', 'user_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leagues', 'clan_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues', 'clan_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leagues', 'user_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clans', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
