"""Add leagues, verificationCodes, restore

Revision ID: 3db5f54cfba9
Revises: 
Create Date: 2024-08-06 02:19:51.683742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db5f54cfba9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'DIAMOND', name='leaguename'), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('clan_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__leagues'))
    )
    op.create_index(op.f('ix__leagues__id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix__leagues__name'), 'leagues', ['name'], unique=True)
    op.create_table('verify_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_code', sa.Integer(), nullable=True),
    sa.Column('verify_code', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__verify_codes'))
    )
    op.create_index(op.f('ix__verify_codes__id'), 'verify_codes', ['id'], unique=False)
    op.create_table('verify_restore_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_code', sa.Integer(), nullable=True),
    sa.Column('verify_code', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__verify_restore_codes'))
    )
    op.create_index(op.f('ix__verify_restore_codes__id'), 'verify_restore_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__verify_restore_codes__id'), table_name='verify_restore_codes')
    op.drop_table('verify_restore_codes')
    op.drop_index(op.f('ix__verify_codes__id'), table_name='verify_codes')
    op.drop_table('verify_codes')
    op.drop_index(op.f('ix__leagues__name'), table_name='leagues')
    op.drop_index(op.f('ix__leagues__id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
