"""add leverage to order table

Revision ID: 43e9a0213e17
Revises: d3f23c3683d0
Create Date: 2024-08-23 05:17:29.858858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e9a0213e17'
down_revision: Union[str, None] = 'd3f23c3683d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('leverage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'leverage')
    # ### end Alembic commands ###
