"""add freeboosters

Revision ID: 4dfbc2574a4e
Revises: 15d91f4a3499
Create Date: 2024-09-20 03:34:12.983812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfbc2574a4e'
down_revision: Union[str, None] = '15d91f4a3499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boosters', sa.Column('turbo_range_active', sa.Boolean(), nullable=True))
    op.add_column('boosters', sa.Column('x_leverage_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boosters', 'x_leverage_active')
    op.drop_column('boosters', 'turbo_range_active')
    # ### end Alembic commands ###
