"""update order table

Revision ID: 5e4f842c757b
Revises: 43e9a0213e17
Create Date: 2024-08-23 05:29:06.315042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4f842c757b'
down_revision: Union[str, None] = '43e9a0213e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contract_pair', sa.String(), nullable=True))
    op.drop_column('orders', 'pair')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pair', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'contract_pair')
    # ### end Alembic commands ###
