"""Upgrade users

Revision ID: 6b312ceb99a2
Revises: e33ad6463c4e
Create Date: 2024-08-06 02:23:09.988696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b312ceb99a2'
down_revision: Union[str, None] = 'e33ad6463c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__users__clan_id__clans'), 'users', 'clans', ['clan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__users__clan_id__clans'), 'users', type_='foreignkey')
    op.drop_column('users', 'clan_id')
    # ### end Alembic commands ###
