"""set nullable=false and default=1 in users table

Revision ID: 7067b63501dc
Revises: 53c6a46b3e6a
Create Date: 2024-08-06 05:06:31.564559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7067b63501dc'
down_revision: Union[str, None] = '53c6a46b3e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
