"""add tasks

Revision ID: b01460841edc
Revises: 0fe5cb6f20de
Create Date: 2024-08-09 18:10:22.611542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b01460841edc'
down_revision: Union[str, None] = '0fe5cb6f20de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('EARN_COINS', 'INVITE_FRIENDS', 'JOIN_SQUAD', name='tasktype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tasks'))
    )
    op.create_index(op.f('ix__tasks__id'), 'tasks', ['id'], unique=False)
    op.create_table('user_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk__user_tasks__task_id__tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__user_tasks__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_tasks'))
    )
    op.create_index(op.f('ix__user_tasks__id'), 'user_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__user_tasks__id'), table_name='user_tasks')
    op.drop_table('user_tasks')
    op.drop_index(op.f('ix__tasks__id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
