"""create orders table

Revision ID: d3f23c3683d0
Revises: 68d6acd6e8d1
Create Date: 2024-08-22 05:32:11.403407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f23c3683d0'
down_revision: Union[str, None] = '68d6acd6e8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('entry_rate', sa.Float(), nullable=True),
    sa.Column('exit_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__orders__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__orders'))
    )
    op.create_index(op.f('ix__orders__id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__orders__id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
