"""Add clans

Revision ID: e33ad6463c4e
Revises: bd390ecea15b
Create Date: 2024-08-06 02:22:31.953029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33ad6463c4e'
down_revision: Union[str, None] = 'bd390ecea15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk__clans__league_id__leagues')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk__clans__owner_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__clans'))
    )
    op.create_index(op.f('ix__clans__id'), 'clans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__clans__id'), table_name='clans')
    op.drop_table('clans')
    # ### end Alembic commands ###
