"""new

Revision ID: 062ce5441a01
Revises: be55b6a336bf
Create Date: 2024-12-16 22:01:38.462896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062ce5441a01'
down_revision = 'be55b6a336bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xboosters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_column('timeout')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xboosters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeout', sa.INTEGER(), nullable=False))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
