"""new

Revision ID: bd58549a7bb4
Revises: 062ce5441a01
Create Date: 2024-12-16 22:07:41.433581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'bd58549a7bb4'
down_revision = '062ce5441a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('xboostersinfo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xboostersinfo', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
