"""clan update

Revision ID: c0fee3fba3df
Revises: 198b224017de
Create Date: 2025-01-24 16:04:30.246797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fee3fba3df'
down_revision = '198b224017de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.drop_column('photo')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
